a = input()
b = a.count('c=')
c = a.count('c-')
d = a.count('dz=')
e = a.count('d-')
f = a.count('lj')
g = a.count('nj')
h = a.count('s=')
i = a.count('z=')
print(len(a) - b - c - d - e - f - g - h - i)
